---
title: "Is there any relationship between temperature anomalies and climate change?"
author: ""
image: climatechange.jpg
date: "2020-10-20"
output:
  html_document:
    theme: flatly
    highlight: zenburn
    number_sections: yes
    toc: yes
    toc_float: yes
    code_folding: show
---



<p>If we wanted to study climate change, we can find data on the <em>Combined Land-Surface Air and Sea-Surface Water Temperature Anomalies</em> in the Northern Hemisphere at <a href="https://data.giss.nasa.gov/gistemp">NASA’s Goddard Institute for Space Studies</a>. The <a href="https://data.giss.nasa.gov/gistemp/tabledata_v3/NH.Ts+dSST.txt">tabular data of temperature anomalies can be found here</a></p>
<p>To define temperature anomalies you need to have a reference, or base, period which NASA clearly states that it is the period between 1951-1980.</p>
<pre class="r"><code>weather &lt;- 
  read_csv(&quot;https://data.giss.nasa.gov/gistemp/tabledata_v3/NH.Ts+dSST.csv&quot;, 
           skip = 1, 
           na = &quot;***&quot;)</code></pre>
<pre class="r"><code>#tidy data
tidyweather &lt;- weather %&gt;% 
  #select the year and months column (i.e. the first 13 columns)
  select(Year:Dec) %&gt;% 
  #change format to long
  pivot_longer(cols = Jan:Dec, names_to = &quot;month&quot;, values_to = &quot;delta&quot;)

#inspect data
glimpse(tidyweather)</code></pre>
<pre><code>## Rows: 1,680
## Columns: 3
## $ Year  &lt;dbl&gt; 1880, 1880, 1880, 1880, 1880, 1880, 1880, 1880, 1880, 1880, 188…
## $ month &lt;chr&gt; &quot;Jan&quot;, &quot;Feb&quot;, &quot;Mar&quot;, &quot;Apr&quot;, &quot;May&quot;, &quot;Jun&quot;, &quot;Jul&quot;, &quot;Aug&quot;, &quot;Sep&quot;, …
## $ delta &lt;dbl&gt; -0.54, -0.38, -0.26, -0.37, -0.11, -0.22, -0.23, -0.24, -0.26, …</code></pre>
<div id="plotting-information" class="section level2">
<h2>Plotting Information</h2>
<p>Let us plot the data using a time-series scatter plot, and add a trendline.</p>
<pre class="r"><code>#create a new variable &quot;date&quot; to ensure our plot is in chronological order
tidyweather &lt;- tidyweather %&gt;%
  mutate(date = ymd(paste(as.character(Year), month, &quot;1&quot;)),
         month = month(date, label=TRUE),
         year = year(date))

ggplot(tidyweather, aes(x=date, y = delta))+
  geom_point()+
  geom_smooth(color=&quot;red&quot;) +
  theme_bw() +
  labs (
    title = &quot;Weather Anomalies&quot; #add a more descriptive title
  )</code></pre>
<p><img src="index_files/figure-html/scatter_plot-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>Is the effect of increasing temperature more pronounced in some months?</p>
<pre class="r"><code>#ordering by month the dataset
tidyweather$month = factor(tidyweather$month, levels = c(&quot;Jan&quot;, &quot;Feb&quot;, &quot;Mar&quot;, &quot;Apr&quot;, &quot;May&quot;, &quot;Jun&quot;, &quot;Jul&quot;, &quot;Aug&quot;, &quot;Sep&quot;, &quot;Oct&quot;, &quot;Nov&quot;, &quot;Dec&quot;))

#scatter plot for each month
ggplot(tidyweather, aes(x = date, y = delta)) +
  geom_point()+
  geom_smooth(color = &quot;red&quot;)+
  facet_wrap(~month)+
  theme_bw()+
  labs(title = &quot;Weather Anomalies for All Months&quot;)+
  NULL</code></pre>
<p><img src="index_files/figure-html/facet_wrap-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>It is sometimes useful to group data into different time periods to study historical data.</p>
<pre class="r"><code>comparison &lt;- tidyweather %&gt;% 
  filter(Year&gt;= 1881) %&gt;%     #remove years prior to 1881
  #create new variable &#39;interval&#39;, and assign values based on criteria below:
  mutate(interval = case_when(
    Year %in% c(1881:1920) ~ &quot;1881-1920&quot;,
    Year %in% c(1921:1950) ~ &quot;1921-1950&quot;,
    Year %in% c(1951:1980) ~ &quot;1951-1980&quot;,
    Year %in% c(1981:2010) ~ &quot;1981-2010&quot;,
    TRUE ~ &quot;2011-present&quot;
  ))</code></pre>
<p>Now that we have the <code>interval</code> variable, we can create a density plot to study the distribution of monthly deviations (<code>delta</code>), grouped by the different time periods we are interested in. Set <code>fill</code> to <code>interval</code> to group and colour the data by different time periods.</p>
<pre class="r"><code>ggplot(comparison, aes(x=delta, fill=interval))+
  geom_density(alpha=0.2) +   #density plot with tranparency set to 20%
  theme_bw() +                #theme
  labs (
    title = &quot;Density Plot for Monthly Temperature Anomalies&quot;,
    y     = &quot;Density&quot;         #changing y-axis label to sentence case
  )</code></pre>
<p><img src="index_files/figure-html/density_plot-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>So far, we have been working with monthly anomalies. However, we might be interested in average annual anomalies. We can do this by using <code>group_by()</code> and <code>summarise()</code>, followed by a scatter plot to display the result.</p>
<pre class="r"><code>#creating yearly averages
average_annual_anomaly &lt;- tidyweather %&gt;% 
  group_by(Year) %&gt;%   #grouping data by Year
  
  # creating summaries for mean delta 
  # use `na.rm=TRUE` to eliminate NA (not available) values 
  summarise(annual_average_delta = mean(delta, na.rm=TRUE)) 

#plotting the data:
ggplot(average_annual_anomaly, aes(x= Year, y= annual_average_delta))+
  geom_point()+
  
  #Fit the best fit line, using LOESS method
  geom_smooth() +
  
  #change to theme_bw() to have white background + black frame around plot
  theme_bw() +
  labs (
    title = &quot;Average Yearly Anomaly&quot;, x = &quot;Year&quot;, y = &quot;Average Annual Delta&quot;
  )                         </code></pre>
<p><img src="index_files/figure-html/averaging-1.png" width="648" style="display: block; margin: auto;" /></p>
</div>
<div id="confidence-interval-for-delta" class="section level2">
<h2>Confidence Interval for <code>delta</code></h2>
<p><a href="https://earthobservatory.nasa.gov/world-of-change/decadaltemp.php">NASA points out on their website</a> that</p>
<p>A one-degree global change is significant because it takes a vast amount of heat to warm all the oceans, atmosphere, and land by that much. In the past, a one- to two-degree drop was all it took to plunge the Earth into the Little Ice Age.</p>
<pre class="r"><code>formula_ci &lt;- comparison %&gt;% 
  # choose the interval 2011-present
  filter(interval == &quot;2011-present&quot;, !is.na(delta)) %&gt;% 
  # calculate summary statistics for temperature deviation (delta) 
  # calculate mean, SD, count, SE, lower/upper 95% CI
  summarise(mean_delta = mean(delta),
            sd_delta = sd(delta),
            count = n(),
            se_delta = sd_delta / sqrt(count),
            t_critical_0.95 = qt(0.95, count - 1),
            margin_error = t_critical_0.95 * se_delta,
            CI_lower = mean_delta - margin_error,
            CI_upper = mean_delta + margin_error
  )

#print out formula_CI
formula_ci %&gt;% 
  select(mean_delta, sd_delta, count, se_delta, CI_lower, CI_upper)</code></pre>
<pre><code>## # A tibble: 1 x 6
##   mean_delta sd_delta count se_delta CI_lower CI_upper
##        &lt;dbl&gt;    &lt;dbl&gt; &lt;int&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1      0.966    0.262   103   0.0259    0.923     1.01</code></pre>
<pre class="r"><code># use the infer package to construct a 95% CI for delta
library(infer)  #include this library in the loadlibraries section
set.seed(1234)

bootstrap_comparison &lt;- comparison %&gt;% 
  # choose the interval 2011-present
  filter(interval == &quot;2011-present&quot;, !is.na(delta)) %&gt;% 
  #variable of interest
  specify(response = delta) %&gt;% 
  #bootstrap sample
  generate(reps = 1000, type = &quot;bootstrap&quot;) %&gt;% 
  #calculate mean of sample
  calculate(stat = &quot;mean&quot;)
  
#get confidence interval
confidence_interval &lt;- bootstrap_comparison %&gt;% 
  get_ci(level = 0.95, type = &quot;percentile&quot;)
  
#print confidence interval
confidence_interval</code></pre>
<pre><code>## # A tibble: 1 x 2
##   lower_ci upper_ci
##      &lt;dbl&gt;    &lt;dbl&gt;
## 1    0.917     1.02</code></pre>
<p>The first and third exhibit - weather anomalies and average yearly anomalies - demonstrate how temperatures have changed for the past 140 years. It shows that temperatures, during this period, have been gradually increasing. During the period, the difference of temperatures between the actual and the base period ranged from around -0.2 to about +1.1 degrees, showing a sharper increase from 1970 onwards. The second exhibit displays that although there are some slight disparities across months, the trendline is very similar for all. The third exhibit portraits a similar conclusion. Through the density plot function, it is possible to notice that each curve is repetitively shifting to the right, i.e. the difference between period’s temperatures and base period’s have been increasing. Lastly, the confidence intervals showcase that, on average, the temperature is approximately +0.966 degrees than the temperature of the base period. Additionally, the data allows us to claim that under a 95% confidence interval the values of delta will range between (+0.923 and +1.01).</p>
</div>
